# Generated by Django 4.0.3 on 2022-03-06 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtest',
            name='customers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingtest',
            name='questions',
            field=models.ManyToManyField(related_name='training_tests', to='training.question'),
        ),
        migrations.AddField(
            model_name='trainingtest',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='training.topic'),
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='questions', to='training.answer'),
        ),
    ]
