# Generated by Django 4.0.3 on 2022-03-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_trainingtestcustomerrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtestcustomerrelation',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
