# Generated by Django 4.0.3 on 2022-03-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_trainingtestcustomerrelation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtest',
            name='customers',
        ),
    ]
