# Generated by Django 4.0.3 on 2022-03-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_remove_answer_question_question_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingtestcustomerrelation',
            old_name='correct_answers',
            new_name='correct_answers_count',
        ),
    ]
