# Generated by Django 4.0.3 on 2022-03-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_alter_question_question_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtest',
            name='slug',
            field=models.SlugField(default='sdf'),
            preserve_default=False,
        ),
    ]
