# Generated by Django 4.0.3 on 2022-03-08 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0015_trainingtest_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingtestcustomerrelation',
            name='correct_answers_count',
        ),
        migrations.RemoveField(
            model_name='trainingtestcustomerrelation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trainingtestcustomerrelation',
            name='passed',
        ),
        migrations.RemoveField(
            model_name='trainingtestcustomerrelation',
            name='training_test',
        ),
        migrations.RemoveField(
            model_name='trainingtestcustomerrelation',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='trainingtestcustomerrelation',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='training.answer'),
        ),
        migrations.AddField(
            model_name='trainingtestcustomerrelation',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training.question'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrainingTestTaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('date_finished', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('training_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingtest')),
            ],
        ),
        migrations.AlterField(
            model_name='trainingtestcustomerrelation',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='training.trainingtesttaker'),
            preserve_default=False,
        ),
    ]
