# Generated by Django 4.0.3 on 2022-03-08 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_remove_trainingtestcustomerrelation_correct_answers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='training_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='training.trainingtest'),
        ),
    ]
